{{ $adminUser := default (randAlphaNum 16) .Values.adminUser }}
{{ $adminPassword := default (randAlphaNum 16) .Values.adminPassword }}
{{- $up := dict }}
{{- range $i, $e := until (default 50 .Values.usernamePoolSize) }}
{{- $_ := set $up (randAlphaNum 16) (randAlphaNum 16) }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.applicationName }}-kafka-auth-pool
  labels:
    component: kafka-operator
    role: auth
    {{- include "standardLabels" . | indent 4 }}
stringData:
  username-pool: |
    {{- range $k, $v := $up }}
    {{ $k }}={{ $v }}
    {{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.applicationName }}-kafka-consumed-auth-pool
  labels:
    component: kafka-operator
    role: auth
    {{- include "standardLabels" . | indent 4 }}
stringData:
  consumed-usernames: ""
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.applicationName }}-kafka-broker-auth
  labels:
    component: kafka-broker
    role: auth
    {{- include "standardLabels" . | indent 4 }}
stringData:
  kafka-server-jaas.conf: |
    KafkaServer {
      org.apache.kafka.common.security.plain.PlainLoginModule required
      username="{{ $adminUser }}"
      password="{{ $adminPassword }}"
      user_{{ $adminUser }}="{{ $adminPassword }}"
      {{- range $k, $v := $up }}
      user_{{ $k }}="{{ $v }}"
      {{- end }}
    };
